android.useAndroidX=true

kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.unsafe.isolated-projects=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# KMK -->
# WebGPU/ImageDecoder v52/v16 target API 37 but do not expose API 37 to Komikku's API 36 code.
android.experimental.disableCompileSdkChecks=true
# KMK <--
